{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "47ffb25f",
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "\n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/Users/jenniferbadger/opt/anaconda3/bin/python\"\n  * The NumPy version is: \"1.19.2\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: dlopen(/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libmkl_rt.dylib\n  Referenced from: <DF7AAC5D-7AE4-3298-B502-88C8949A3035> /Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so\n  Reason: tried: '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/usr/local/lib/libmkl_rt.dylib' (no such file), '/usr/lib/libmkl_rt.dylib' (no such file, not in dyld cache)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/numpy/core/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     21\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 22\u001b[0;31m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmultiarray\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     23\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mImportError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexc\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/numpy/core/multiarray.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 12\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0moverrides\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     13\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0m_multiarray_umath\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/numpy/core/overrides.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m from numpy.core._multiarray_umath import (\n\u001b[0m\u001b[1;32m      8\u001b[0m     add_docstring, implement_array_function, _get_implementing_args)\n",
      "\u001b[0;31mImportError\u001b[0m: dlopen(/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libmkl_rt.dylib\n  Referenced from: <DF7AAC5D-7AE4-3298-B502-88C8949A3035> /Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so\n  Reason: tried: '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/usr/local/lib/libmkl_rt.dylib' (no such file), '/usr/lib/libmkl_rt.dylib' (no such file, not in dyld cache)",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-a8a57ea53472>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    138\u001b[0m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0m_distributor_init\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    139\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 140\u001b[0;31m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    141\u001b[0m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    142\u001b[0m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcompat\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/numpy/core/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     46\u001b[0m \"\"\" % (sys.version_info[0], sys.version_info[1], sys.executable,\n\u001b[1;32m     47\u001b[0m         __version__, exc)\n\u001b[0;32m---> 48\u001b[0;31m     \u001b[0;32mraise\u001b[0m \u001b[0mImportError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     49\u001b[0m \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     50\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0menvkey\u001b[0m \u001b[0;32min\u001b[0m \u001b[0menv_added\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/Users/jenniferbadger/opt/anaconda3/bin/python\"\n  * The NumPy version is: \"1.19.2\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: dlopen(/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libmkl_rt.dylib\n  Referenced from: <DF7AAC5D-7AE4-3298-B502-88C8949A3035> /Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so\n  Reason: tried: '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/python3.8/site-packages/numpy/core/../../../../libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jenniferbadger/opt/anaconda3/lib/libmkl_rt.dylib' (no such file), '/Users/jenniferbadger/opt/anaconda3/bin/../lib/libmkl_rt.dylib' (no such file), '/usr/local/lib/libmkl_rt.dylib' (no such file), '/usr/lib/libmkl_rt.dylib' (no such file, not in dyld cache)\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6e667d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cartopy\n",
    "import cartopy.crs\n",
    "import cartopy.feature as cfeature\n",
    "import seaborn \n",
    "import geopandas \n",
    "import earthpy \n",
    "import xarray \n",
    "import regionmask"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
